In [1]:
import cv2
import numpy as np

In [11]:
# template matching is finding tempalte in large image
img = cv2.imread("messi5.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi_face.jpg", 0)
w,h =template.shape[::-1]

res = cv2.matchTemplate(gray_img, template, cv2.TM_CCOEFF_NORMED)
print(res)
threshold = 0.94
loc = np.where(res >= threshold)
print(loc)
for pt in zip(*loc[::-1]): #if there are many face in picture
    cv2.rectangle(img, pt, (pt[0]+w, pt[1] + h), (0,0,255), 2)

cv2.imshow('Image', img)
cv2.imshow('template', template)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 0.04590957  0.02492268  0.00350578 ...  0.1331739   0.13252516
   0.12799199]
 [ 0.03644399  0.01738107 -0.00178124 ...  0.12055782  0.11765827
   0.11163652]
 [ 0.02616353  0.00932175 -0.00776539 ...  0.10842744  0.10390328
   0.09628399]
 ...
 [ 0.22693364  0.2153092   0.20560218 ... -0.09364472 -0.08020408
  -0.07588955]
 [ 0.22718237  0.21924375  0.21610412 ... -0.10811316 -0.09903625
  -0.09328807]
 [ 0.22984974  0.22069359  0.21116294 ... -0.12015773 -0.11462525
  -0.10919443]]
(array([69], dtype=int64), array([201], dtype=int64))


In [15]:
# template matching is finding tempalte in large image
img = cv2.imread("messi5.jpg")
gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
template = cv2.imread("messi_face.jpg", 0)
w,h =template.shape[::-1]

res = cv2.matchTemplate(gray_img, template, cv2.TM_CCORR_NORMED)
print(res)
threshold = 0.99
loc = np.where(res >= threshold)
print(loc)
for pt in zip(*loc[::-1]): #if there are many face in picture
    cv2.rectangle(img, pt, (pt[0]+w, pt[1] + h), (0,0,255), 2)

cv2.imshow('Image', img)
cv2.imshow('template', template)

cv2.waitKey(0)
cv2.destroyAllWindows()

[[0.7062213  0.6987395  0.6911824  ... 0.7955926  0.7942308  0.7920781 ]
 [0.7029056  0.6960262  0.6891777  ... 0.79171634 0.789759   0.7871734 ]
 [0.69963926 0.6934643  0.6872766  ... 0.78773427 0.78531045 0.78225434]
 ...
 [0.8431039  0.8426693  0.8422922  ... 0.8108306  0.8135912  0.8152211 ]
 [0.84316677 0.84287065 0.8427444  ... 0.8091657  0.81150484 0.8133119 ]
 [0.84332395 0.8429777  0.84260136 ... 0.8076383  0.8096236  0.81142116]]
(array([69], dtype=int64), array([201], dtype=int64))
